version: '3'

services:
  nginx:
    container_name: nginx
    # hostname: webserver
    build:
      context: requirements/nginx
    volumes:
      - wordpress:/var/www/html
    # depends_on:
      # wordpress:
        # condition: service_healthy
    image: "nginx"
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://localhost || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    image: "wordpress"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9000 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_started

  mariadb:
    container_name: mariadb
    hostname: "mariadb"
    volumes:
      - mariadb:/var/lib/mysql
    build:
      context: requirements/mariadb
    image: mariadb
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - inception
    expose:
      - "3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$MDB_USER -p$MDB_PASS || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: volume
      device: /home/spagliar/data/mysql
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: volume
      device: /home/spagliar/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
